[pytest]

#addopts = -s --html=./report/report.html
#--reruns 3 --reruns-delay=2
#addopts = -s --alluredir ./report/result

#配置allure报告，-clean-alluredir 清除allure_results文件夹中上次的报告，无该命令会进行累加生成
addopts = -vs --alluredir=./allure_results --clean-alluredir
#测试用例的路径
testpaths =./test_cases
#模块名的规则
python_files = test_*.py
#类名的规则
python_classes = Test*
#方法名的规则
python_functions = test